```yaml
name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/942176962636/locations/global/workloadIdentityPools/githubpool/providers/github-provider"
          service_account: "my-first-yash@project-2d68d63d-fb3f-4f10-805.iam.gserviceaccount.com"

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - name: Build Docker Image
        run: |
          docker build \
            -t us-central1-docker.pkg.dev/project-2d68d63d-fb3f-4f10-805/app-repo/demo-app:${{ github.sha }} \
            ./app

      - name: Push Docker Image
        run: |
          docker push \
            us-central1-docker.pkg.dev/project-2d68d63d-fb3f-4f10-805/app-repo/demo-app:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy demo-app \
            --image us-central1-docker.pkg.dev/project-2d68d63d-fb3f-4f10-805/app-repo/demo-app:${{ github.sha }} \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated


